# Homebrew formula for the tap hongnoul/homebrew-tap, so the user-facing
# command is `brew install hongnoul/tap/gwae`.
#
# This file is generated by gwae's release workflow (bump-tap job).
# Do not edit the SHA/version lines by hand — edit packaging/homebrew/gwae.rb in hongnoul/gwae instead.
class Gwae < Formula
  desc "Scrolling terminal multiplexer for macOS; panes never shrink"
  homepage "https://github.com/hongnoul/gwae"
  license "MIT"

  if Hardware::CPU.arm?
    url "https://github.com/hongnoul/gwae/releases/download/v1.7.0/gwae-aarch64-apple-darwin.tar.gz"
    sha256 "9336ac38fb4d104fbb5b529951a222e8cbd75aedcb6d9670e267aec8e7aa02f5"
  else
    url "https://github.com/hongnoul/gwae/releases/download/v1.7.0/gwae-x86_64-apple-darwin.tar.gz"
    sha256 "ca3ee873b6a9cd06a7881732a5a6ac590cf750db801cbea7ab0a17a9f3398edc"
  end

  def install
    bin.install "gwae"
  end

  def caveats
    <<~EOS
      ▄▄▄▄ ▄ ▄
       ▄ █ █▄█   welcome to gwae — panes that never shrink.
       █ █ █ █   installed and on your PATH, nothing to configure.
       █ ▀ █ █   ready. run 'gwae' to get started.
      ▀▀▀▀ ▀ ▀
    EOS
  end

  test do
    system "#{bin}/gwae", "doctor"
  end
end
