# Homebrew formula for the tap hongnoul/homebrew-tap, so the user-facing
# command is `brew install hongnoul/tap/gwae`.
#
# This file is generated by gwae's release workflow (bump-tap job).
# Do not edit the SHA/version lines by hand — edit packaging/homebrew/gwae.rb in hongnoul/gwae instead.
class Gwae < Formula
  desc "Scrolling terminal multiplexer for macOS; panes never shrink"
  homepage "https://github.com/hongnoul/gwae"
  license "MIT"

  if Hardware::CPU.arm?
    url "https://github.com/hongnoul/gwae/releases/download/v1.6.0/gwae-aarch64-apple-darwin.tar.gz"
    sha256 "8268af379ca1a1987151bee6c7ec4652aae5e8308a2afde399b675298b823082"
  else
    url "https://github.com/hongnoul/gwae/releases/download/v1.6.0/gwae-x86_64-apple-darwin.tar.gz"
    sha256 "404900f4bb15e3c168d5454255671d09a06c1ced19864c07c4c2181f1fd251d3"
  end

  def install
    bin.install "gwae"
  end

  def caveats
    <<~EOS
      ready. run 'gwae' to get started.
    EOS
  end

  test do
    system "#{bin}/gwae", "doctor"
  end
end
